Add versions command (#9)
* Add versions command

* update

* fix

* Add --all --installed

* add test for --all

diff --git a/src/dpv b/src/dpv
--- a/src/dpv
+++ b/src/dpv
@@ -14,7 +14,7 @@
 #
 set -e
 
-function cmd_help() {
+cmd_help() {
 	_load_config_vars
 
 	echo "dpv $CFG_VERSION"
@@ -24,32 +24,63 @@ function cmd_help() {
 	echo "  dpv help        - display these instructions"
 	echo "  dpv list        - lists virtualenvs managed by dpv"
 	echo "  dpv where       - display the virtualenv directory"
-	echo "  dpv version     - display version"
+	echo "  dpv versions    - display available python versions"
+	echo "    --all         - include all versions rather than a simplified list"
+	echo "    --installed   - only display versions that are currently installed"
 	echo "  dpv instrument  - instruments dpv"
 	echo "  dpv run [cmd]   - runs command inside virtualenv [default: \$SHELL]"
-	echo
-	echo "aliases:"
-	echo "  dpv -h / dpv help"
-	echo "  dpv -v / dpv version"
-	echo "  dpv -l / dpv ls / dpv list"
 	echo
 	echo "global arguments:"
 	echo "  -q / --quiet    - do not show logs"
 	echo
+	echo "aliases:"
+	echo "  dpv -h / dpv help"
+	echo "  dpv -v / dpv versions"
+	echo "  dpv -l / dpv ls / dpv list"
+	echo
 }
 
-function cmd_version() {
+cmd_versions() {
 	_load_config_vars
-	echo "$CFG_VERSION"
+
+	echo "retrieving available python versions..."
+	echo
+
+	if [[ "$CFG_AVAILABLE_INSTALL_METHODS" =~ "pyenv;" ]]; then
+		case "$1" in
+		--installed)
+			if result=$(_run_command_log_failure "pyenv versions --bare --skip-aliases"); then
+				echo "pyenv: $(echo "$result" | cut -d/ -f1 | uniq | sort --version-sort | tr '\n' ' ')"
+			fi
+			;;
+		--all)
+			if result=$(_run_command_log_failure "pyenv install --list"); then
+				echo "pyenv: $(echo "$result" | sed 's/ //g' | tail -n +2 | tr '\n' ' ')"
+			fi
+			;;
+		*)
+			local supported_python_versions_grep_regex='^\(3\.\([789]\|1[^.]\)\.0$\)\|^\(4\.[0-9]\+\.0$\)'
+			if result=$(_run_command_log_failure "pyenv install --list"); then
+				echo "pyenv: $(echo "$result" | sed 's/ //g' | grep "$supported_python_versions_grep_regex" | sed 's/\.0$//' | tr '\n' ' ')"
+			fi
+			;;
+		esac
+	fi
+
+	if [[ "$CFG_AVAILABLE_INSTALL_METHODS" =~ "homebrew;" ]]; then
+		if result=$(_run_command_log_failure "brew search python"); then
+			echo "homebrew: $(echo "$result" | grep -o 'python@[^ ]\+' | cut -d@ -f2 | sort --version-sort | tr '\n' ' ')"
+		fi
+	fi
 }
 
-function cmd_where() {
+cmd_where() {
 	_load_config_vars
 	_load_python_vars
 	echo "$VENV_DIR"
 }
 
-function cmd_instrument() {
+cmd_instrument() {
 	trap - EXIT
 
 	# https://stackoverflow.com/a/13864829
@@ -61,7 +92,7 @@ function cmd_instrument() {
 	fi
 }
 
-function cmd_list() {
+cmd_list() {
 	case "$1" in
 	--plain | *)
 		_load_config_vars
@@ -70,7 +101,7 @@ function cmd_list() {
 	esac
 }
 
-function cmd_run() {
+cmd_run() {
 	_load_config_vars
 	_load_python_vars
 
@@ -81,19 +112,7 @@ function cmd_run() {
 	_run_command "$@"
 }
 
-function err_detecting_python_version() {
-	_log "- failed to determine python version for $PWD"
-
-	_print_exit_shell
-}
-
-function err_activate_virtualenv() {
-	_log "- failed to activate virtualenv $VENV_DIR"
-
-	_print_exit_shell
-}
-
-function __main() {
+__main() {
 	trap '_error_handling $?' EXIT
 
 	CMD=""
@@ -133,8 +152,8 @@ function __main() {
 		cmd_run "$@"
 		;;
 
-	version | -v)
-		cmd_version
+	versions | -v)
+		cmd_versions "${@:1}"
 		;;
 
 	help | -h)
@@ -152,26 +171,33 @@ function __main() {
 
 ERR_CANNOT_DETERMINE_PYTHON_VERSION=2
 ERR_CANNOT_ACTIVATE_VIRTUALENV=3
+ERR_NO_INSTALL_METHOD=4
 
-function _error_handling() {
+_error_handling() {
 	case "$1" in
 
 	"$ERR_CANNOT_DETERMINE_PYTHON_VERSION")
-		err_detecting_python_version
+		echo "failed to determine python version for $PWD"
 		;;
 
 	"$ERR_CANNOT_ACTIVATE_VIRTUALENV")
-		err_activate_virtualenv
+		echo "failed to activate virtualenv $VENV_DIR"
+		;;
+
+	"$ERR_NO_INSTALL_METHOD")
+		echo "no installation methods found"
 		;;
 
 	esac
+
+	_print_exit_shell
 
 	if [ -z "${DPV_INSTRUMENT+x}" ]; then
 		_print_logs
 	fi
 }
 
-function _run_command() {
+_run_command() {
 	if [ -n "${DPV_SHELL+x}" ]; then
 		trap - EXIT
 		exit 0
@@ -186,27 +212,38 @@ function _run_command() {
 	fi
 }
 
-function _load_config_vars() {
+_load_config_vars() {
 	CFG_LOG_FILE=$(mktemp "${TMPDIR:-/tmp/}dpv_logs.XXXXX")
 	CFG_INSTALL_METHOD="${DPV_INSTALL_METHOD}"
+	CFG_AVAILABLE_INSTALL_METHODS=""
 	CFG_QUIET="${ARG_QUIET:-${DPV_QUIET:-0}}"
 
 	# https://stackoverflow.com/a/677212
 	if hash pyenv 2>/dev/null; then
-		if [ "$CFG_INSTALL_METHOD" == "pyenv" ] || [ "$CFG_INSTALL_METHOD" == "" ]; then
+		CFG_AVAILABLE_INSTALL_METHODS+="pyenv;"
+		if [ "$CFG_INSTALL_METHOD" == "" ] || [ "$CFG_INSTALL_METHOD" == "pyenv" ]; then
+			_log "- pyenv is installed and is the preferred installation method"
 			CFG_INSTALL_METHOD="pyenv"
-			_log "- pyenv is installed (preferred)"
 		else
-			_log "- pyenv is installed but will not be used"
+			_log "- pyenv is installed"
 		fi
+	else
+		_log "- pyenv is not installed"
 	fi
 	if hash brew 2>/dev/null; then
-		if [ "$CFG_INSTALL_METHOD" == "homebrew" ] || [ "$CFG_INSTALL_METHOD" == "" ]; then
+		CFG_AVAILABLE_INSTALL_METHODS+="homebrew;"
+		if [ "$CFG_INSTALL_METHOD" == "" ] || [ "$CFG_INSTALL_METHOD" == "homebrew" ]; then
+			_log "- homebrew is installed and is the preferred installation method"
 			CFG_INSTALL_METHOD="homebrew"
-			_log "- homebrew is installed (preferred)"
 		else
-			_log "- homebrew is installed but will not be used"
+			_log "- homebrew is installed"
 		fi
+	else
+		_log "- homebrew is not installed"
+	fi
+
+	if [ "$CFG_INSTALL_METHOD" == "" ]; then
+		exit "$ERR_NO_INSTALL_METHOD"
 	fi
 
 	CFG_VERSION="1.0.0"
@@ -216,7 +253,7 @@ function _load_config_vars() {
 	mkdir -p "$CFG_VENVS_DIR"
 }
 
-function _load_python_vars() {
+_load_python_vars() {
 	PY_VERSION=$(_get_python_version)
 	PY_PREFIX=$(_get_python_prefix)
 
@@ -232,7 +269,7 @@ function _load_python_vars() {
 	VENV_DIR=$CFG_VENVS_DIR/$PY_VERSION/$(basename "$PWD")-$PY_VERSION
 }
 
-function _get_python_version() {
+_get_python_version() {
 	local python_version
 	if [ -f "runtime.txt" ]; then
 		python_version=$(sed 's/^python\-//' <runtime.txt)
@@ -262,7 +299,7 @@ function _get_python_version() {
 	echo "$python_version"
 }
 
-function _get_python_prefix() {
+_get_python_prefix() {
 	case "$CFG_INSTALL_METHOD" in
 	pyenv)
 		pyenv prefix "$PY_VERSION"
@@ -273,32 +310,32 @@ function _get_python_prefix() {
 	esac
 }
 
-function _create_venv_if_not_exists() {
+_create_venv_if_not_exists() {
 	if [ ! -d "$VENV_DIR" ]; then
 		"$PY_EXECUTABLE" -m venv "$VENV_DIR"
 	fi
 }
 
-function _print_venv_activate() {
+_print_venv_activate() {
 	echo "source $VENV_DIR/bin/activate || exit $ERR_CANNOT_ACTIVATE_VIRTUALENV"
 }
 
-function _plain_list() {
+_plain_list() {
 	find "$CFG_VENVS_DIR" -maxdepth 2 -mindepth 2
 }
 
-function _print_exit_shell() {
+_print_exit_shell() {
 	if [ -n "${DPV_SHELL+x}" ]; then
 		echo "unset DPV_SHELL"
 		echo "exit 1"
 	fi
 }
 
-function _log() {
-	echo "$@" >>"$CFG_LOG_FILE"
+_log() {
+	echo -e "$@" >>"$CFG_LOG_FILE"
 }
 
-function _print_logs() {
+_print_logs() {
 	if [[ "$CFG_QUIET" -eq 0 ]]; then
 		echo
 		echo "logs:"
@@ -307,7 +344,21 @@ function _print_logs() {
 	fi
 }
 
-function _util_count_char() {
+_run_command_log_failure() {
+	tmpfile=$(mktemp)
+
+	# shellcheck disable=SC2068
+	if $@ &>"$tmpfile"; then
+		cat "$tmpfile"
+		exit 0
+	else
+		_log "- failed to retrieve python versions from homebrew:"
+		_log "$(sed 's/^/  > /' <"$tmpfile")"
+		exit 1
+	fi
+}
+
+_util_count_char() {
 	echo "$1" | tr -cd "$2" | wc -c
 }
 
