Add --no-pyenv and --no-homebrew

diff --git a/src/dpv b/src/dpv
--- a/src/dpv
+++ b/src/dpv
@@ -26,7 +26,7 @@
 # 5. Command variants functions should be named "cmd_{command name}_{variant}"
 # 6. Initialization functions should be named "init_{name}"
 # 7. Short-hand functions differently than utilities are not pure
-# 8. Utilities are "pure" functions and should be prefixed with "_util_"
+# 8. Utilities are "pure" functions and should be prefixed with "__"
 # 9. Exit codes should be stored in constants prefixed with "ERR_"
 
 set -e
@@ -45,16 +45,20 @@ cmd_help() {
 	echo "dpv $CFG_VERSION"
 	echo
 	echo "usage:"
-	echo "  dpv             - installs virtualenv for the current directory"
-	echo "  dpv help        - display these instructions"
-	echo "  dpv list        - lists virtualenvs managed by dpv"
-	echo "  dpv run [cmd]   - runs command inside virtualenv [default: \$SHELL]"
-	echo "  dpv versions    - display python versions"
-	echo "    --all         - include all versions rather than a simplified list"
-	echo "    --installed   - only display versions that are currently installed"
-	echo "  dpv where       - display the virtualenv directory"
+	echo "  dpv help             - display these instructions"
+	echo "  dpv list             - list virtualenvs created with dpv"
+	echo "  dpv run [command]    - run command inside virtualenv [default: \$SHELL]"
+	echo "    --python [version] - specify python version"
+	echo "  dpv versions         - display installed python versions"
+	echo "    --available        - display available ptyhon versions"
+	echo "    --all              - display all versions rather than a simplified list"
+	echo
+	echo "global arguments:"
+	echo "  --no-pyenv           - disable pyenv detection"
+	echo "  --no-homebrew        - disable homebrew detection"
 	echo
 	echo "aliases:"
+	echo "  dpv / dpv run"
 	echo "  dpv -h / dpv help"
 	echo "  dpv -l / dpv ls / dpv list"
 	echo "  dpv -v / dpv versions"
@@ -65,41 +69,59 @@ cmd_versions() {
 	init_config_vars
 
 	case "$1" in
-	--installed)
-		echo "retrieving installed python versions..."
+	"")
+		echo "installed python versions"
 		echo
-		(_has_pyenv) && (
-			echo -n "pyenv: "
-			_cmd_versions_installed_pyenv
-		)
-		(_has_homebrew) && (
-			echo -n "homebrew: "
-			_cmd_versions_installed_homebrew
-		)
+		if (_has_pyenv); then
+			if result=$(_get_installed_versions_pyenv); then
+				echo "pyenv: $(echo "$result" | __pretty_print_delimited_ws)"
+			else
+				echo "pyenv: failed, check logs"
+			fi
+		fi
+		if (_has_homebrew); then
+			if result=$(_get_installed_versions_homebrew); then
+				echo "homebrew: $(echo "$result" | __pretty_print_delimited_ws)"
+			else
+				echo "homebrew: failed, check logs"
+			fi
+		fi
 		;;
 	--all)
-		echo "retrieving all available python versions..."
+		echo "all python versions available"
 		echo
-		(_has_pyenv) && (
-			echo -n "pyenv: "
-			_cmd_versions_all_pyenv
-		)
-		(_has_homebrew) && (
-			echo -n "homebrew: "
-			_cmd_versions_available_homebrew
-		)
+		if (_has_pyenv); then
+			if result=$(_get_all_versions_pyenv); then
+				echo "pyenv: $(echo "$result" | __pretty_print_delimited_ws)"
+			else
+				echo "pyenv: failed, check logs"
+			fi
+		fi
+		if (_has_homebrew); then
+			if result=$(_get_available_versions_homebrew); then
+				echo "homebrew: $(echo "$result" | __pretty_print_delimited_ws)"
+			else
+				echo "homebrew: failed, check logs"
+			fi
+		fi
 		;;
-	"")
-		echo "retrieving available python versions..."
+	--available)
+		echo "available python versions"
 		echo
-		(_has_pyenv) && (
-			echo -n "pyenv: "
-			_cmd_versions_available_pyenv
-		)
-		(_has_homebrew) && (
-			echo -n "homebrew: "
-			_cmd_versions_available_homebrew
-		)
+		if (_has_pyenv); then
+			if result=$(_get_available_versions_pyenv); then
+				echo "pyenv: $(echo "$result" | __pretty_print_delimited_ws)"
+			else
+				echo "pyenv: failed, check logs"
+			fi
+		fi
+		if (_has_homebrew); then
+			if result=$(_get_available_versions_homebrew); then
+				echo "homebrew: $(echo "$result" | __pretty_print_delimited_ws)"
+			else
+				echo "homebrew: failed, check logs"
+			fi
+		fi
 		;;
 	*)
 		echo "unknown argument: $1"
@@ -107,64 +129,14 @@ cmd_versions() {
 	esac
 }
 
-_cmd_versions_installed_pyenv() {
-	if result=$(_run_command_log_failure "pyenv versions --bare --skip-aliases"); then
-		echo "$result" | cut -d/ -f1 | uniq | sort --version-sort | tr '\n' ' '
-		echo
-	else
-		echo "failed, check logs"
-	fi
-}
-
-_cmd_versions_all_pyenv() {
-	if result=$(_run_command_log_failure "pyenv install --list"); then
-		echo "$result" | sed 's/ //g' | tail -n +2 | tr '\n' ' '
-		echo
-	else
-		echo "failed, check logs"
-	fi
-}
-
-_cmd_versions_available_pyenv() {
-	local supported_python_versions_grep_regex='^\(3\.\([789]\|1[^.]\)\.0$\)\|^\(4\.[0-9]\+\.0$\)'
-	if result=$(_run_command_log_failure "pyenv install --list"); then
-		echo "$result" | sed 's/ //g' | grep "$supported_python_versions_grep_regex" | _util_strip_point_zero | tr '\n' ' '
-		echo
-	else
-		echo "failed, check logs"
-	fi
-}
-
-_cmd_versions_available_homebrew() {
-	if result=$(_run_command_log_failure "brew search python"); then
-		echo "$result" | grep -o 'python@[^ ]\+' | cut -d@ -f2 | sort --version-sort | tr '\n' ' '
-		echo
-	fi
-}
-
-_cmd_versions_installed_homebrew() {
-	if result=$(_run_command_log_failure "brew list"); then
-		echo "$result" | grep 'python@' | cut -d@ -f2 | sort --version-sort | tr '\n' ' '
-		echo
-	fi
-}
-
-cmd_where() {
-	init_config_vars
-	init_virtualenv_vars
-
-	echo "$VENV_DIR"
-}
-
 cmd_internal_instrument() {
 	trap - EXIT
 
 	# https://stackoverflow.com/a/13864829
-	if [ -n "${DPV_SHELL+x}" ]; then
+	if [ -n "${DPV_VENV_DIR+x}" ]; then
 		init_config_vars
-		init_virtualenv_vars
 
-		echo "source $VENV_DIR/bin/activate || exit $ERR_CANNOT_ACTIVATE_VIRTUALENV"
+		echo "source $DPV_VENV_DIR/bin/activate || exit $ERR_CANNOT_ACTIVATE_VIRTUALENV"
 	fi
 }
 
@@ -175,21 +147,38 @@ cmd_list() {
 }
 
 cmd_run() {
+	for i in "$@"; do
+		case "$i" in
+		--python)
+			shift
+			ARG_PYTHON_VERSION="$1"
+			shift
+			;;
+		esac
+	done
+
 	init_config_vars
 	init_virtualenv_vars
 
-	if [ ! -d "$VENV_DIR" ]; then
+	if [ -d "$VENV_DIR" ]; then
+		_log "- found existing virtualenv at $VENV_DIR"
+	else
+		init_python_vars
+
 		"$PY_EXECUTABLE" -m venv "$VENV_DIR"
+		echo -e "path = $PWD\nversion = $VENV_PYTHON_VERSION" >"$VENV_DIR/dpv.cfg"
+		_log "- created virtualenv at $VENV_DIR"
 	fi
 
-	if [ -n "${DPV_SHELL+x}" ]; then
+	if [ -n "${DPV_VENV_DIR+x}" ]; then
 		trap - EXIT
 		exit 0
 	fi
 
 	if [ "$#" -eq 0 ]; then
+		echo "dpv - python $VENV_PYTHON_VERSION activated"
 		_print_logs
-		DPV_SHELL=1 "$SHELL"
+		DPV_VENV_DIR=$VENV_DIR "$SHELL"
 		trap - EXIT
 	else
 		PATH=$VENV_DIR/bin:$PATH "$@"
@@ -201,12 +190,19 @@ cmd_run() {
 #
 
 init_config_vars() {
+	#
+	# Initialize CFG_* variables
+	#
 	CFG_LOG_FILE=$(mktemp "${TMPDIR:-/tmp/}dpv_logs.XXXXX")
 	CFG_INSTALL_METHOD="${DPV_INSTALL_METHOD}"
 	CFG_AVAILABLE_INSTALL_METHODS=""
+	CFG_NO_PYENV=${ARG_NO_PYENV:-0}
+	CFG_NO_HOMEBREW=${ARG_NO_HOMEBREW:-0}
 
-	# https://stackoverflow.com/a/677212
-	if hash pyenv 2>/dev/null; then
+	if [ "$CFG_NO_PYENV" -eq 1 ]; then
+		_log "- pyenv disabled"
+	elif hash pyenv 2>/dev/null; then
+		# https://stackoverflow.com/a/677212
 		CFG_AVAILABLE_INSTALL_METHODS+="pyenv;"
 		if [ "$CFG_INSTALL_METHOD" == "" ] || [ "$CFG_INSTALL_METHOD" == "pyenv" ]; then
 			_log "- pyenv is installed and is the preferred installation method"
@@ -217,7 +213,10 @@ init_config_vars() {
 	else
 		_log "- pyenv is not installed"
 	fi
-	if hash brew 2>/dev/null; then
+
+	if [ "$CFG_NO_HOMEBREW" -eq 1 ]; then
+		_log "- homebrew disabled"
+	elif hash brew 2>/dev/null; then
 		CFG_AVAILABLE_INSTALL_METHODS+="homebrew;"
 		if [ "$CFG_INSTALL_METHOD" == "" ] || [ "$CFG_INSTALL_METHOD" == "homebrew" ]; then
 			_log "- homebrew is installed and is the preferred installation method"
@@ -241,39 +240,116 @@ init_config_vars() {
 }
 
 init_virtualenv_vars() {
-	if [ -f "runtime.txt" ]; then
-		PY_VERSION=$(sed 's/^python\-//' <runtime.txt)
-		_log "- parsed python version $PY_VERSION from runtime.txt file"
-	else
-		_log "- cannot find $PWD/runtime.txt file"
+	#
+	# Initialize VENV_ variables
+	#
+	# Depends on init_config_vars
+	#
+	VENV_PYTHON_VERSION="$ARG_PYTHON_VERSION"
+
+	# try to locate existing virtualenv
+	while IFS= read -r file; do
+		local path
+		local version
+		while IFS= read -r line; do
+			if [[ "$line" =~ ^path\ *=\ *(.*) ]]; then
+				path="${BASH_REMATCH[1]}"
+			elif [[ "$line" =~ ^version\ *=\ *(.*) ]]; then
+				version="${BASH_REMATCH[1]}"
+			fi
+		done <"$file"
+		if [[ "$path" == "$PWD" ]]; then
+			if [[ "$ARG_PYTHON_VERSION" == "" ]] || [[ "$ARG_PYTHON_VERSION" == "$version" ]]; then
+				VENV_DIR=$(dirname "$file")
+				VENV_PYTHON_VERSION=$version
+			fi
+		fi
+	done < <(find "$CFG_VENVS_DIR" -name dpv.cfg -type f -mindepth 3 -maxdepth 3)
+
+	# try to detect python version from runtime.txt file
+	if [ "$VENV_PYTHON_VERSION" == "" ]; then
+		_log "- no existing virtualenvs found for $PWD"
+
+		if [ -f "runtime.txt" ]; then
+			VENV_PYTHON_VERSION=$(sed 's/^python\-//' <runtime.txt)
+			_log "- parsed python version $VENV_PYTHON_VERSION from runtime.txt file"
+		else
+			_log "- no $PWD/runtime.txt file found"
+		fi
+
+		# normalize python version according to install method
+		case "$CFG_INSTALL_METHOD" in
+		pyenv)
+			VENV_PYTHON_VERSION=$(echo "$VENV_PYTHON_VERSION" | __normalize_version_pyenv)
+			;;
+		homebrew)
+			VENV_PYTHON_VERSION=$(echo "$VENV_PYTHON_VERSION" | __normalize_version_homebrew)
+			;;
+		esac
+	fi
+
+	# otherwise, prompt user about the python version
+	if [ "$VENV_PYTHON_VERSION" == "" ]; then
+		local default_version=""
+		if (_has_pyenv); then
+			_cache_installed_versions_pyenv
+			default_version=$(cut -d: -f2 <(echo "$_CACHED_INSTALLED_VERSIONS_PYENV"))
+		elif (_has_homebrew); then
+			_cache_installed_versions_homebrew
+			default_version=$(cut -d: -f2 <(echo "$_CACHED_INSTALLED_VERSIONS_HOMEBREW"))
+		fi
+		read -rp "python version [$default_version]: " VENV_PYTHON_VERSION
+		VENV_PYTHON_VERSION=${VENV_PYTHON_VERSION:-$default_version}
+		_log "- using python version from input: $VENV_PYTHON_VERSION"
+	fi
+
+	if [ "$VENV_PYTHON_VERSION" == "" ]; then
 		exit "$ERR_CANNOT_DETERMINE_PYTHON_VERSION"
 	fi
 
+	VENV_DIR=$CFG_VENVS_DIR/$VENV_PYTHON_VERSION/$(basename "$PWD")-$VENV_PYTHON_VERSION
+}
+
+init_python_vars() {
+	#
+	# Initialize PY_ variables
+	#
+	# Depends on init_config_vars, init_virtualenv_vars
+	#
+	local python_version="$VENV_PYTHON_VERSION"
+
 	case "$CFG_INSTALL_METHOD" in
 	pyenv)
-		_log "- checking installation of $PY_VERSION with pyenv"
-		_log "$(sed s'/^/  > /' <(pyenv install "$PY_VERSION" --skip-existing 2>&1))"
-		_log "  ok"
+		_cache_installed_versions_pyenv
+		python_version=$(echo "$python_version" | __normalize_version_pyenv)
+		if [[ "$_CACHED_INSTALLED_VERSIONS_PYENV" != *":$python_version:"* ]]; then
+			echo "installing python $python_version using pyenv"
+			pyenv install "$python_version" 2>&1 | sed 's/^/  > /'
+			echo "ok"
+		else
+			_log "- python $python_version is currently installed by pyenv"
+		fi
 
-		PY_PREFIX=$(pyenv prefix "$PY_VERSION")
+		PY_PREFIX=$(pyenv prefix "$python_version")
 		PY_EXECUTABLE="$PY_PREFIX/bin/python"
 		;;
 	homebrew)
-		if [ "$(_util_count_char "$PY_VERSION" '.')" -gt 1 ]; then
-			python_version=$(cut -d. -f1,2 <(echo "$PY_VERSION"))
-			_log "- homebrew only supports 3.y python versions, using $PY_VERSION"
+		_cache_installed_versions_homebrew
+		python_version=$(echo "$python_version" | __normalize_version_homebrew)
+		if [ "$python_version" != "$VENV_PYTHON_VERSION" ]; then
+			_log "- homebrew only supports 3.y python versions, using $python_version"
 		fi
 
-		_log "- checking installation of $PY_VERSION with homebrew"
-		_log "$(sed 's/^/  > /' <(HOMEBREW_NO_AUTO_UPDATE=1 brew install "python@$PY_VERSION" 2>&1))"
-		_log "  ok"
+		if [[ "$_CACHED_INSTALLED_VERSIONS_HOMEBREW" != *":$python_version:"* ]]; then
+			echo "installing python $python_version using homebrew"
+			HOMEBREW_NO_AUTO_UPDATE=1 brew install "python@$python_version" 2>&1 | sed 's/^/  > /'
+			echo "ok"
+		fi
 
-		PY_PREFIX=$(brew --prefix "python@$PY_VERSION")
+		PY_PREFIX=$(brew --prefix "python@$python_version")
 		PY_EXECUTABLE="$PY_PREFIX/bin/python3"
 		;;
 	esac
-
-	VENV_DIR=$CFG_VENVS_DIR/$PY_VERSION/$(basename "$PWD")-$PY_VERSION
 }
 
 #
@@ -283,11 +359,37 @@ init_virtualenv_vars() {
 main() {
 	trap 'error_handling $?' EXIT
 
-	case "$1" in
-	where)
-		cmd_where
-		;;
+	CMD=""
+	CMD_ARGS=""
 
+	# parse global arguments
+	for i in "$@"; do
+		case $i in
+		--no-pyenv)
+			ARG_NO_PYENV=1
+			;;
+		--no-homebrew)
+			ARG_NO_HOMEBREW=1
+			;;
+		--*)
+			if [ "$CMD" == "" ]; then
+				CMD="run"
+			fi
+			CMD_ARGS+=" $i"
+			;;
+		*)
+			if [ "$CMD" == "" ]; then
+				CMD="$i"
+			else
+				CMD_ARGS+=" $i"
+			fi
+			;;
+		esac
+	done
+
+	CMD_ARGS=${CMD_ARGS:1} # drop leading space
+
+	case "$CMD" in
 	internal-instrument)
 		cmd_internal_instrument
 		;;
@@ -297,11 +399,13 @@ main() {
 		;;
 
 	run | "")
-		cmd_run "${@:2}"
+		# shellcheck disable=2086
+		cmd_run $CMD_ARGS
 		;;
 
 	versions | -v)
-		cmd_versions "${@:2}"
+		# shellcheck disable=2086
+		cmd_versions $CMD_ARGS
 		;;
 
 	help | -h)
@@ -333,7 +437,7 @@ error_handling() {
 		;;
 
 	"$ERR_NO_INSTALL_METHOD")
-		echo "no installation methods found"
+		echo "no installation method to pick"
 		;;
 
 	esac
@@ -341,8 +445,8 @@ error_handling() {
 	if [ -z "${DPV_INSTRUMENT+x}" ]; then
 		_print_logs
 	else
-		if [ -n "${DPV_SHELL+x}" ]; then
-			echo "unset DPV_SHELL"
+		if [ -n "${DPV_VENV_DIR+x}" ]; then
+			echo "unset DPV_VENV_DIR"
 			echo "exit 1"
 		fi
 	fi
@@ -385,16 +489,81 @@ _has_homebrew() {
 	[[ "$CFG_AVAILABLE_INSTALL_METHODS" =~ "homebrew;" ]] || exit 1
 }
 
+_get_installed_versions_pyenv() {
+	if result=$(_run_command_log_failure "pyenv versions --bare --skip-aliases"); then
+		echo "$result" | cut -d/ -f1 | uniq | sort --version-sort | __nl_to_delimited
+	else
+		exit 1
+	fi
+}
+
+_get_all_versions_pyenv() {
+	if result=$(_run_command_log_failure "pyenv install --list"); then
+		echo "$result" | sed 's/ //g' | tail -n +2 | __nl_to_delimited
+	else
+		exit 1
+	fi
+}
+
+_get_available_versions_pyenv() {
+	local supported_python_versions_grep_regex='^\(3\.\([789]\|1[^.]\)\.0$\)\|^\(4\.[0-9]\+\.0$\)'
+	if result=$(_run_command_log_failure "pyenv install --list"); then
+		echo "$result" | sed 's/ //g' | grep "$supported_python_versions_grep_regex" | __nl_to_delimited
+	else
+		exit 1
+	fi
+}
+
+_get_available_versions_homebrew() {
+	if result=$(_run_command_log_failure "brew search python"); then
+		echo "$result" | grep -o 'python@[^ ]\+' | cut -d@ -f2 | sort --version-sort | __nl_to_delimited
+	else
+		exit 1
+	fi
+}
+
+_get_installed_versions_homebrew() {
+	if result=$(_run_command_log_failure "brew list"); then
+		echo "$result" | grep 'python@' | cut -d@ -f2 | sort --version-sort | __nl_to_delimited
+	else
+		exit 1
+	fi
+}
+
+_cache_installed_versions_pyenv() {
+	if [ -n "${_CACHED_INSTALLED_VERSIONS_PYENV-x}" ]; then
+		_CACHED_INSTALLED_VERSIONS_PYENV=$(_get_installed_versions_pyenv)
+	fi
+}
+
+_cache_installed_versions_homebrew() {
+	if [ -n "${_CACHED_INSTALLED_VERSIONS_HOMEBREW-x}" ]; then
+		_CACHED_INSTALLED_VERSIONS_HOMEBREW=$(_get_installed_versions_homebrew)
+	fi
+}
+
 #
 # Utilities
 #
 
-_util_count_char() {
-	echo "$1" | tr -cd "$2" | wc -c
+__pretty_print_delimited_ws() {
+	# Transforms multiple lines in one separated by spaces
+	sed -E 's/^:|:$//g' | tr ':' ' '
 }
 
-_util_strip_point_zero() {
-	sed 's/\.0$//'
+__nl_to_delimited() {
+	# a\nb\n\nc\n\n => :a:b:c:
+	tr '\n' ':' | sed -E 's/^|$|:+/:/g'
+}
+
+__normalize_version_pyenv() {
+	# 3.7 => 3.7.0
+	sed 's/^\([0-9]*\)\.\([0-9]*\)$/\1.\2.0/'
+}
+
+__normalize_version_homebrew() {
+	# 3.7.12 => 3.7
+	sed 's/^\([0-9]*\)\.\([0-9]*\)\.\([0-9]*\)$/\1.\2/'
 }
 
 main "$@"
